# Generated by Django 2.1.4 on 2018-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='Address',
        ),
        migrations.AddField(
            model_name='employee_details',
            name='Address_off',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='Address_perm',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee_details',
            name='Address_pres',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
