# Generated by Django 2.1.4 on 2018-12-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_auto_20181222_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='Address_off',
            new_name='Address_Office',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='Address_perm',
            new_name='Address_Permanent',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='Address_pres',
            new_name='Address_Present',
        ),
    ]
