# Generated by Django 2.1.4 on 2018-12-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20181222_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_details',
            old_name='Address_Office',
            new_name='Office_Address',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='Address_Permanent',
            new_name='Permanent_Address',
        ),
        migrations.RenameField(
            model_name='employee_details',
            old_name='Address_Present',
            new_name='Present_Address',
        ),
    ]
